name: nimitnshah
favicon: null
layout_spectrum: 0.3758417994249612
typography_spectrum: 0.4179309136234224
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2546097894664854
  lightness: 0.7000119490548968
  saturation: 0.015015186043456197
  rhythmicContrast: 0.9066935193259269
purpose: []
